### ISSUE TITLE
Feature request: Add ability to change the opacity of the cover css box

### ISSUE THREAD

**Issue by hydroid7** [james-fray/youtube-stop-autoplay#1]
Hi there,
I've installed your add-on on the PC of my Grandma and she wanted to change the opacity of the css cover box. But since there is no option to do this, I've made it by hand. It is possible to add a simple text box or a slider to change the opacity?

**Comment by james-fray** [comment]
Sure, the new version has an slider in the options page to change the opacity.

**Comment by hydroid7** [comment]
Thanks! :sunglasses:
