### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Altaira** [james-fray/youtube-stop-autoplay#3]
This extension worked fine until today (2017-01-31). There is also a comment in the review section on Mozilla where someone else notes that the extension has quit working.

**Comment by Phlipper8** [comment]
Same as Altaira, extension has quit working and I am left with Youtube autoplay that has no slider button to turn it off.

**Comment by james-fray** [comment]
Thanks for the report. Version 0.1.4 fixes this issue
