### ISSUE TITLE
Stopped working as of 9th april 2020

### ISSUE THREAD

**Issue by dutchgecko** [james-fray/youtube-stop-autoplay#5]
Standard youtube behaviour has returned - at the end of a video, a new video is queued up to be played and there is no slider to disable this.

Let me know if I need to provide any further information.

Browser is Firefox v75.0

**Comment by doomprompt** [comment]
Can confirm dutchgecko. Linux Mint 19.0.

**Comment by FIammen** [comment]
Can confirm the same problem. It is so annoying getting back to clicking the blue slider at every session. Why is the setting to turn off autoplay not saved in a cookie or something?

Firefix 75.0 Win10 v. 18363

**Comment by james-fray** [comment]
Should be fixed by the new release. Thanks for the report.
